film/urls.py
from django.urls import path, reverse_lazy
from .views import HomePage, HomeFilms, DetailFilm, SearchMovie, ProfileEdit, CreateAccount
from django.contrib.auth import views as auth_view

app_name='film'
urlpatterns = [
    path(
        '',
        HomePage.as_view(),
        name='homepage'
    ),
    path(
        'login',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login'
    ),
    path(
        'logout',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout'
    ),
    path(
        'films',
        HomeFilms.as_view(),
        name='films'
    ),
    path(
        'search',
        SearchMovie.as_view(),
        name='search'
    ),
    path(
        'films/<int:pk>',
        DetailFilm.as_view(),
        name='detailFilm'),
    path(
        'profileEdit/<int:pk>',
        ProfileEdit.as_view(),
        name='profileEdit'
    ),
    path(
        'createAccount',
        CreateAccount.as_view(),
        name='createAccount'
    ),
    path(
        'changePassword',
        auth_view.PasswordChangeView.as_view(template_name='profileedit.html',
                                             success_url=reverse_lazy('film:films')),
        name='changePassword'
    ),
]

myNetflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('film.urls', namespace='film')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

film/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.


LIST_CATEGORY = (
    ('ACTION', 'Action'),
    ('DRAMA', 'Drama'),
    ('COMEDY', 'Comedy')
)

#criar o filme
class Film(models.Model):
    title = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_film')
    description = models.TextField(max_length=1000)
    category = models.CharField(max_length=15, choices=LIST_CATEGORY)
    visualization = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=timezone.now)
    related_movies = models.ManyToManyField("Film", blank=True)

    def __str__(self):
        return self.title

class Chapter(models.Model):
    film = models.ForeignKey("Film", related_name="chapters", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.title


class User(AbstractUser):
    movies_watched = models.ManyToManyField("Film")

filme/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


LIST_CATEGORY = (
    ('ACTION', 'Action'),
    ('DRAMA', 'Drama'),
    ('COMEDY', 'Comedy')
)

#criar o filme
class Filme(models.Model):
    title = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_film')
    description = models.TextField(max_length=1000)
    category = models.CharField(max_length=15, choices=LIST_CATEGORY)
    visualization = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Chapter(models.Model):
    film = models.ForeignKey("Filme", related_name="chapters", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.title

film/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms

class FormHomePage(forms.Form):
    email = forms.EmailField(label=False)


class CreateAccountForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

film/views.py
from django.shortcuts import render, redirect, reverse
from .models import Film, User
from .forms import CreateAccountForm, FormHomePage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# def homepage(request):
#    return render(request, 'homepage.html')

class HomePage(FormView):
    template_name = "homepage.html"
    form_class = FormHomePage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('film:films')
        else:
            return super().get(request, *args, *kwargs)

    def get_success_url(self):
        email = self.request.POST.get('email')
        user = User.objects.filter(email=email)
        if user:
            return reverse('film:login')
        else:
            return reverse('film:createAccount')


# def homefilms(request):
#     context = {}
#     list_films = Filme.objects.all()
#     context['list_films'] = list_films
#     return render(request, 'homefilms.html', context)

class HomeFilms(LoginRequiredMixin, ListView):
    template_name = "homefilms.html"
    model = Film

    def open_movie(self):
        print('clicked')


class SearchMovie(LoginRequiredMixin, ListView):
    template_name = "search.html"
    model = Film

    def get_queryset(self):
        wordSearch = self.request.GET.get('q')
        if wordSearch:
            object_list = self.model.objects.filter(title__icontains=wordSearch)
            return object_list
        else:
            return None


class DetailFilm(LoginRequiredMixin, DetailView):
    template_name = "detailfilm.html"
    model = Film

    def get(self, request, *args, **kwargs):
        film = self.get_object()
        film.visualization += 1
        film.save()
        
        user = request.user
        user.movies_watched.add(film)

        return super().get(request, *args, *kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailFilm, self).get_context_data(**kwargs)
        related_movies = self.model.objects.exclude(pk=self.get_object().pk).filter(category=self.get_object().category)[0:5]
        context["related_movies"] = related_movies

        return context

class ProfileEdit(LoginRequiredMixin, UpdateView):
    template_name = "profileedit.html"
    model = User
    fields = ['first_name', 'last_name', 'email', 'username']

    def get_success_url(self):
        return reverse('film:films')


class CreateAccount(FormView):
    template_name = "createAccount.html"
    form_class = CreateAccountForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('film:login')

filme/views.py
from django.shortcuts import render
from .models import Filme
from django.views.generic import TemplateView, ListView, DetailView

# Create your views here.

# def homepage(request):
#    return render(request, 'homepage.html')

class HomePage(TemplateView):
    template_name = "homepage.html"


# def homefilms(request):
#     context = {}
#     list_films = Filme.objects.all()
#     context['list_films'] = list_films
#     return render(request, 'homefilms.html', context)

class HomeFilms(ListView):
    template_name = "homefilms.html"
    model = Filme


class SearchMovie(ListView):
    template_name = "search.html"
    model = Filme

    def get_queryset(self):
        wordSearch = self.request.GET.get('q')
        if wordSearch:
            object_list = self.model.objects.filter(title__icontains=wordSearch)
            return object_list
        else:
            return None


class DetailFilm(DetailView):
    template_name = "detailfilm.html"
    model = Filme

    def get(self, request, *args, **kwargs):
        film = self.get_object()
        film.visualization += 1
        film.save()

        return super().get(request, *args, *kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailFilm, self).get_context_data(**kwargs)
        related_movies = self.model.objects.exclude(pk=self.get_object().pk).filter(category=self.get_object().category)[0:5]
        context["related_movies"] = related_movies

        return context

film/templates/createAccount.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
create Account
{% endblock %}

{% block head %}
    <style>
        .form-text {
            color: gray
        }

    </style>
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Create an account to continue</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Create Account</button>
            </form>
        </div>
    </header>

    <footer class=" px-5 py-10">
        <ul class="flex justify-between items-center">
            <li>&copy; 2023</li>
            <li> Made with Python (Django)</li>
        </ul>
    </footer>
{% endblock %}

film/templates/detailfilm.html
{% extends 'base.html' %}

{% block title %}
Film
{% endblock %}

{% block content %}


<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{object.title}}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{object.description | slice:"100"}}
            </p>
            <div class="flex my-4">
                <a href="{{ object.chapters.first.video}}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Description
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.description }}
                    <br>
                    Visualizations: {{ object.visualization }}
                </p>
            </div>

            {% if object.chapters.all|length > 1 %}
            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Chapters
                </h2>
                {% for chapter in object.chapters.all %}
                    <h3 class='text-lg'>
                        <a href="{{ chapter.video }}">
                            <p>Chapter {{ forloop.counter }}: {{ chapter.title }}</p>
                        </a>
                    </h3>
                {% endfor %}

            </div>
            {% endif %}

        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Related movies
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for movie in object.related_movies.all %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'film:detailFilm' movie.pk %}">
                            <img src="{{ movie.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>

{% endblock %}

film/templates/homefilms.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Movies
{% endblock %}

{% block head %}
<style>
   $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(4,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(4, auto);
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }

    }

     #sec1go, #sec1back, #sec2go, #sec2back, #sec3go, #sec3back,
     #sec4go, #sec4back, #sec5go, #sec5back, #sec6go, #sec6back {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;

      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }

    }
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
 </style>
{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url({{ most_recent_movie.thumb.url}});">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ most_recent_movie.title }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ most_recent_movie.description }}
                </p>
                <div class="flex my-4">
                    <a href="{% url 'film:detailFilm' most_recent_movie.pk %}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium " >
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>


        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    New movies
                </h2>
                <div class="wrapper">
                  <section id="section1">
                    <a id="sec1back" href="#section2" class="arrow__btn">‹</a>
                    {% for movie in recently_movies_list %}
                        {% if forloop.counter < 5 %}
                          <div class="item">
                              <a href="{% url 'film:detailFilm' movie.pk %}">
                                <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                        {% endif %}
                    {% endfor %}
                    <a id="sec1go" href="#section2" class="arrow__btn">›</a>
                  </section>
                    {% if recently_movies_list|length > 4 %}
                      <section id="section2">
                        <a id="sec2back" href="#section1" class="arrow__btn">‹</a>
                          {% for movie in recently_movies_list %}
                            {% if forloop.counter >= 5 %}
                              <div class="item">
                                  <a href="{% url 'film:detailFilm' movie.pk %}">
                                    <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                            {% endif%}
                          {% endfor %}
                        <a id="sec2go" href="#section1" class="arrow__btn">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Top movies
                </h2>
                <div class="wrapper">
                  <section id="section3">
                    <a id="sec3back" href="#section4" class="arrow__btn">‹</a>
                       {% for movie in top_movies_list %}
                         {% if forloop.counter < 5 %}
                              <div class="item">
                                  <a href="{% url 'film:detailFilm' movie.pk %}">
                                    <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                         {% endif %}
                       {% endfor %}
                    <a id="sec3go" href="#section4" class="arrow__btn">›</a>
                  </section>
                    {% if top_movies_list|length > 4 %}
                      <section id="section4">
                        <a id="sec4back" href="#section3" class="arrow__btn">‹</a>
                          {% for movie in top_movies_list %}
                            {% if forloop.counter >= 5 %}
                              <div class="item">
                                  <a href="{% url 'film:detailFilm' movie.pk %}">
                                    <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                            {% endif %}
                          {% endfor %}
                        <a id="sec4go" href="#section3" class="arrow__btn">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

        {% if watched_movies_list|length >= 4 %}
            <section class='bg-primary_black flex justify-center py-10'>
                <div class="p-8 w-10/12 relative" >
                    <h2 class="text-gray-200 text-2xl font-medium">
                        Watched Movies
                    </h2>
                    <div class="wrapper">
                      <section id="section5">
                        <a id="sec5back" href="#section6" class="arrow__btn">‹</a>
                           {% for movie in watched_movies_list %}
                            {% if forloop.counter < 5 %}
                              <div class="item">
                                  <a href="{% url 'film:detailFilm' movie.pk %}">
                                    <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                            {% endif %}
                          {% endfor %}
                        <a id="sec5go" href="#section6" class="arrow__btn">›</a>
                      </section>
                        {% if watched_movies_list|length == 8 %}
                          <section id="section6">
                            <a id="sec6back" href="#section5" class="arrow__btn">‹</a>
                              {% for movie in watched_movies_list %}
                                {% if forloop.counter >= 5 %}
                                  <div class="item">
                                      <a href="{% url 'film:detailFilm' movie.pk %}">
                                        <img src="{{ movie.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                      </a>
                                  </div>
                                {% endif%}
                              {% endfor %}
                            <a id="sec6go" href="#section5" class="arrow__btn">›</a>
                          </section>
                        {% endif %}
                    </div>
                </div>
            </section>
        {% endif %}
    </main>
{% endblock %}

film/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
MyNetflix
{% endblock %}

{% block head %}
    <style>
        #id_email{
            width: 100%;
            color: #000000;
            padding: 5px 5px;
        }
    </style>
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
            style="background-image: url('{% static 'images/background_netflix.jpg' %}')">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                MyNetflix movies and series, all in one place.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Watch wherever you want. Cancel whenever you want.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Want to get started? Enter your email below to access.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Sign in
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Made with Python (Django)</li>
            <li>MyFlix</li>
        </ul>
    </footer>
{% endblock %}

film/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Login to continue</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Login</button>
            </form>
            <small>
               Don't have an account yet? <p><a href="{% url 'film:createAccount' %}">Click here to create an account</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
        </ul>
    </footer>
{% endblock %}

film/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Logout
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">You log out. Thanks for spending some quality time with the web site today.</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-5">
            <a href="{% url 'film:login' %}"><button class="bg-red-600  py-1 px-3 text-white md:text-lg rounded-md">Sign in</button></a>
            <a href="{% url 'film:createAccount' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Sign up</button></a>
            </div>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Made with Python (Django)</li>
        </ul>
    </footer>
{% endblock %}

film/templates/profileedit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
edit profile
{% endblock %}

{% block head %}
    <style>
        .form-text {
            color: gray
        }

    </style>
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-2">Edit the fields below to edit your profile</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Update</button>
            </form>
            <small><a href="{% url 'film:changePassword' %}">Do you want to change your password?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Made with Python (Django)</li>
        </ul>
    </footer>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-5/12" src="{% static 'images/mynetflix.png' %}">
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'film:search' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="q" value="{{ request.GET.q }}" placeholder="search...">
                <input type="submit" value=""/>
            </form>
        </div>
        {% endif %}
        <div class="mr-2">
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'film:logout' %}">
                    {% csrf_token %}
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md" type="submit">Logout</button>
                </form>
            {% else %}
                <a href="{% url 'film:login' %}">
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">Sign in</button>
                </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'film:profileEdit' user.pk %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Profile Edit</button>
            </a>
        </div>
        {% endif %}
    </div>
</nav>